feat: add fish + config

diff --git a/install_powerful_shell b/install_powerful_shell
--- a/install_powerful_shell
+++ b/install_powerful_shell
@@ -5,23 +5,24 @@
 source install_helpers.sh
 print_commence "$BASH_SOURCE"
 
-function __add_zsh_to_profile() {
+function __add_fish_to_profile() {
   {
     echo ''
-    echo "# Added by $USER for zsh"
-    echo 'export SHELL=$(which zsh)'
-    echo '[ -z "$ZSH_VERSION" ] && exec $SHELL -l'
-  } >>"$HOME/.profile"
+    echo "# Added by $USER for fish"
+    echo 'export SHELL=$(which fish)'
+    echo '[ -z "$FISH_VERSION" ] && exec $SHELL -l'
+  } >> "$HOME/.profile"
 
+  chmod 644 "$HOME/.profile"
   source "$HOME/.profile"
 }
 
 function __change_shell() {
-  [ "$SHELL" == "$(which zsh)" ] && echo -e "zsh is already the default shell" && return
-  echo "User shell is not zsh. Changing..."
-  if ! chsh -s "$(which zsh)"; then
-    echo "Failed with chsh. Setting zsh to .profile"
-    __add_zsh_to_profile
+  [ "$SHELL" == "$(which fish)" ] && echo -e "fish is already the default shell" && return
+  echo "User shell is not fish. Changing..."
+  if ! chsh -s "$(which fish)"; then
+    echo "Failed with chsh. Setting fish to .profile"
+    __add_fish_to_profile
   fi
 }
 
@@ -34,7 +35,16 @@ function __install_oh-my-zsh() {
 function __install_antigen() {
   [[ -f "$HOME/antigen.zsh" ]] && echo -e "antigen is already installed" && return
   echo -e "\nInstalling antigen"
-  curl -L git.io/antigen >"$HOME/antigen.zsh"
+  curl -L git.io/antigen > "$HOME/antigen.zsh"
+}
+
+function __install_fish_config() {
+  if [ ! -d "$HOME/.config/fish" ]; then
+    mkdir -p "$HOME/.config/fish"
+    cp fish_config/* "$HOME/.config/fish/"
+  else
+    echo -e "fish config already exists, copy fish_config/* to ~/.config/fish/ manually if you want to update"
+  fi
 }
 
 update_file bashrc "$HOME/.bashrc"
@@ -45,6 +55,8 @@ update_file aliases "$HOME/.aliases"
 update_file gitattributes "$HOME/.gitattributes"
 
 install_tool curl
-install_tool zsh
+install_tool fish
+
 __install_antigen
 __change_shell
+__install_fish_config
